# Generated by Django 4.2.5 on 2023-09-18 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'создан'), (1, 'оплачен'), (2, 'в пути'), (3, 'доставлен')], default=0),
        ),
    ]
